// supabase/functions/send-signature-invite/index.ts
import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { Resend } from "npm:resend@4.0.0";

// ---------------------------------------------------------------------------
// ENV + CLIENT
// ---------------------------------------------------------------------------
const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
const SERVICE_ROLE_KEY =
  Deno.env.get("SERVICE_ROLE_KEY") ?? Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  throw new Error("Missing SUPABASE_URL or SERVICE_ROLE_KEY");
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  global: { fetch },
});

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

// ✅ Use your verified domain by default
const FROM_EMAIL =
  Deno.env.get("SIGNATURE_FROM_EMAIL") ?? "signatures@oasisintlholdings.com";

// ✅ This is the public React signing page (/sign), *not* the old sign.html
const SIGNING_BASE_URL =
  Deno.env.get("SIGNING_BASE_URL") ??
  "https://sign.oasisintlholdings.com/sign";

const resend = RESEND_API_KEY ? new Resend(RESEND_API_KEY) : null;

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers":
        "Content-Type, Authorization, apikey, x-client-info",
    },
  });
}

serve(async (req) => {
  // CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      status: 200,
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers":
          "Content-Type, Authorization, apikey, x-client-info",
      },
    });
  }

  if (req.method !== "POST") {
    return json({ ok: false, error: "Use POST" }, 405);
  }

  try {
    // -----------------------------------------------------------------------
    // 1) Pick the oldest pending email job
    // -----------------------------------------------------------------------
    const { data: jobs, error: jobsErr } = await supabase
      .from("signature_email_queue")
      .select(
        [
          "id",
          "envelope_id",
          "party_id",
          "to_email",
          "to_name",
          "document_title",
          "status",
          "attempts",
        ].join(", "),
      )
      .eq("status", "pending")
      .order("created_at", { ascending: true })
      .limit(1);

    if (jobsErr) {
      console.error("signature_email_queue query error", jobsErr);
      return json(
        { ok: false, error: "Failed to read pending signature jobs." },
        500,
      );
    }

    if (!jobs || jobs.length === 0) {
      // Nothing to send – not an error
      return json({
        ok: true,
        message: "No pending signature email jobs.",
      });
    }

    const job = jobs[0];

    // -----------------------------------------------------------------------
    // 2) Construct signing URL for the public /sign page
    // -----------------------------------------------------------------------
    const signingUrl =
      `${SIGNING_BASE_URL}?envelope_id=${encodeURIComponent(
        job.envelope_id,
      )}&party_id=${encodeURIComponent(job.party_id)}`;

    // -----------------------------------------------------------------------
    // 3) Send the email (Resend or just log in dev)
    // -----------------------------------------------------------------------
    const subject =
      job.document_title ??
      `Signature requested – Oasis Digital Parliament Ledger`;
    const to = job.to_email;

    const html = `
      <p>Hi ${job.to_name ?? ""},</p>
      <p>You have a governance document ready for signature in the Oasis Digital Parliament Ledger.</p>
      <p><a href="${signingUrl}">Click here to review and sign</a>.</p>
      <p>Document: <strong>${job.document_title ?? "Ledger record"}</strong></p>
      <p>This secure link was generated by CI-Forge.</p>
    `;

    if (!resend || !RESEND_API_KEY) {
      // Dev mode – don't actually send, just log
      console.warn(
        "RESEND_API_KEY not configured – logging email instead of sending.",
      );
      console.log({ to, subject, signingUrl });
    } else {
      await resend.emails.send({
        from: FROM_EMAIL,
        to,
        subject,
        html,
      });
    }

    // -----------------------------------------------------------------------
    // 4) Mark job as sent
    // -----------------------------------------------------------------------
    const { error: updateErr } = await supabase
      .from("signature_email_queue")
      .update({
        status: "sent",
        attempts: (job.attempts ?? 0) + 1,
        sent_at: new Date().toISOString(),
        error_message: null,
      })
      .eq("id", job.id);

    if (updateErr) {
      console.error("signature_email_queue update error", updateErr);
      return json(
        {
          ok: false,
          error: "Email sent, but failed to update queue row.",
        },
        500,
      );
    }

    return json({
      ok: true,
      message: "Signature invitation email sent.",
      job_id: job.id,
      signing_url: signingUrl,
    });
  } catch (e) {
    console.error("Unexpected error in send-signature-invite", e);
    return json(
      {
        ok: false,
        error: "Unexpected server error",
        details: String(e),
      },
      500,
    );
  }
});
